import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Alata } from "next/font/google";
import { Providers } from "./redux/provider";
import { ToastContainer } from "react-toastify";

const alata = Alata({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${alata.className}`}>
      <body>
        {/*<ToastContainer />*/}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
