import "./globals.css";
import { Alata } from "next/font/google";

const alata = Alata({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${alata.className}`}>
      <body>{children}</body>
    </html>
  );
}
